remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

title: [Michelle Le Data Analytics Portfolio]
description: [A showcase of some projects that I have completed during my time with TripleTen (formerly Practicum) as well as some passion projects.]
